modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ModdingForBlockheads/DefaultOptions/issues"
[[mods]]
modId="defaultoptions"
version="${file.jarVersion}"
displayName="Default Options"
displayURL="https://blay09.net/mods/defaultoptions"
logoFile="defaultoptions-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''

'''
[[dependencies.defaultoptions]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.defaultoptions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
[[dependencies.defaultoptions]]
    modId="balm"
    mandatory=true
    versionRange="[1.6.0,)"
    ordering="NONE"
    side="BOTH"
